server:
  port: 9008
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: Holmes
    url: jdbc:mysql://localhost:3306/keke
    username: root
    password: root
SnowFlake:
  worker-id: 1
  datacenter-id: 1
  sequence-id: 1